"""empty message

Revision ID: 9e3f5ff1fd62
Revises: 
Create Date: 2025-12-20 12:30:22.204437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e3f5ff1fd62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbox_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('login', name=op.f('uq_user_login'))
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analytics_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], name=op.f('fk_video_analytics_id_analytics')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_video_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video')),
    sa.UniqueConstraint('analytics_id', name=op.f('uq_video_analytics_id')),
    sa.UniqueConstraint('video_path', name=op.f('uq_video_video_path'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('analytics')
    # ### end Alembic commands ###
